### ISSUE TITLE
simple makes then will see UT failed. what is root cause?

### ISSUE THREAD

**Issue by gwnet** [pmem/llpl#3]
root@ubuntu:/home/wayne/llpl# make && make tests
g++ -O3 -DNDEBUG -fPIC -I/usr/lib/jvm/java-1.8.0-openjdk-amd64/include -I/usr/lib/jvm/java-1.8.0-openjdk-amd64/include/linux -o target/cppbuild/lib_llpl_Transaction.o -c src/main/cpp/lib_llpl_Transaction.cpp
g++ -O3 -DNDEBUG -fPIC -I/usr/lib/jvm/java-1.8.0-openjdk-amd64/include -I/usr/lib/jvm/java-1.8.0-openjdk-amd64/include/linux -o target/cppbuild/persistent_heap.o -c src/main/cpp/persistent_heap.cpp
g++ -O3 -DNDEBUG -fPIC -I/usr/lib/jvm/java-1.8.0-openjdk-amd64/include -I/usr/lib/jvm/java-1.8.0-openjdk-amd64/include/linux -o target/cppbuild/lib_llpl_AnyMemoryBlock.o -c src/main/cpp/lib_llpl_AnyMemoryBlock.cpp
g++ -O3 -DNDEBUG -fPIC -I/usr/lib/jvm/java-1.8.0-openjdk-amd64/include -I/usr/lib/jvm/java-1.8.0-openjdk-amd64/include/linux -o target/cppbuild/lib_llpl_AnyHeap.o -c src/main/cpp/lib_llpl_AnyHeap.cpp
g++ -Wl,-soname,target/cppbuild/libllpl.so -o target/cppbuild/libllpl.so target/cppbuild/lib_llpl_Transaction.o target/cppbuild/persistent_heap.o target/cppbuild/lib_llpl_AnyMemoryBlock.o target/cppbuild/lib_llpl_AnyHeap.o -fPIC -O3 -DNDEBUG -shared -lpmem -lpmemobj -Wl,-rpath,/usr/local/lib:/usr/local/lib64
mkdir -p target/classes
mkdir -p target/test_classes
/usr/lib/jvm/java-1.8.0-openjdk-amd64/bin/javac -Xlint:unchecked -proc:none -XDenableSunApiLintControl -d target/classes -cp target/classes:lib src/main/java/lib/llpl/package-info.java src/main/java/lib/llpl/TransactionalHeap.java src/main/java/lib/llpl/TransactionException.java src/main/java/lib/llpl/MemoryBlock.java src/main/java/lib/llpl/Range.java src/main/java/lib/llpl/UnboundedMemoryBlock.java src/main/java/lib/llpl/PersistentUnboundedMemoryBlock.java src/main/java/lib/llpl/Heap.java src/main/java/lib/llpl/AbstractMemoryBlock.java src/main/java/lib/llpl/AbstractPersistentMemoryBlock.java src/main/java/lib/llpl/TransactionalMemoryBlock.java src/main/java/lib/llpl/TransactionalUnboundedMemoryBlock.java src/main/java/lib/llpl/Stats.java src/main/java/lib/llpl/AbstractTransactionalMemoryBlock.java src/main/java/lib/llpl/Transaction.java src/main/java/lib/llpl/AnyMemoryBlock.java src/main/java/lib/llpl/PersistentMemoryBlock.java src/main/java/lib/llpl/HeapException.java src/main/java/lib/llpl/AnyHeap.java src/main/java/lib/llpl/PersistentHeap.java
Note: src/main/java/lib/llpl/AnyHeap.java uses internal proprietary API that may be removed in a future release.
Note: Recompile with -Xlint:sunapi for details.
/usr/lib/jvm/java-1.8.0-openjdk-amd64/bin/javac -Xlint:unchecked -proc:none -XDenableSunApiLintControl -cp target/classes:lib:src/examples/array src/examples/array/*.java;  /usr/lib/jvm/java-1.8.0-openjdk-amd64/bin/javac -Xlint:unchecked -proc:none -XDenableSunApiLintControl -cp target/classes:lib:src/examples/string_store src/examples/string_store/*.java;
/usr/lib/jvm/java-1.8.0-openjdk-amd64/bin/javac -Xlint:unchecked -proc:none -XDenableSunApiLintControl -cp target/classes:lib:src -d target/test_classes src/test/java/lib/llpl/*.java;
/usr/lib/jvm/java-1.8.0-openjdk-amd64/bin/java -ea -cp target/classes:lib:target/test_classes -Djava.library.path=target/cppbuild lib/llpl/CopyMemoryTest;  /usr/lib/jvm/java-1.8.0-openjdk-amd64/bin/java -ea -cp target/classes:lib:target/test_classes -Djava.library.path=target/cppbuild lib/llpl/PersistentMemoryBlockTest;  /usr/lib/jvm/java-1.8.0-openjdk-amd64/bin/java -ea -cp target/classes:lib:target/test_classes -Djava.library.path=target/cppbuild lib/llpl/MemoryBlockCollectionTest;  /usr/lib/jvm/java-1.8.0-openjdk-amd64/bin/java -ea -cp target/classes:lib:target/test_classes -Djava.library.path=target/cppbuild lib/llpl/MemoryBlockFreeTest;  /usr/lib/jvm/java-1.8.0-openjdk-amd64/bin/java -ea -cp target/classes:lib:target/test_classes -Djava.library.path=target/cppbuild lib/llpl/MemoryBlockEqualityTest;  /usr/lib/jvm/java-1.8.0-openjdk-amd64/bin/java -ea -cp target/classes:lib:target/test_classes -Djava.library.path=target/cppbuild lib/llpl/MemoryBlockTest;  /usr/lib/jvm/java-1.8.0-openjdk-amd64/bin/java -ea -cp target/classes:lib:target/test_classes -Djava.library.path=target/cppbuild lib/llpl/MultipleHeapTest;  /usr/lib/jvm/java-1.8.0-openjdk-amd64/bin/java -ea -cp target/classes:lib:target/test_classes -Djava.library.path=target/cppbuild lib/llpl/MultipleTransactionalHeapTest;  /usr/lib/jvm/java-1.8.0-openjdk-amd64/bin/java -ea -cp target/classes:lib:target/test_classes -Djava.library.path=target/cppbuild lib/llpl/SetMemoryTest;  /usr/lib/jvm/java-1.8.0-openjdk-amd64/bin/java -ea -cp target/classes:lib:target/test_classes -Djava.library.path=target/cppbuild lib/llpl/TransactionTest;  /usr/lib/jvm/java-1.8.0-openjdk-amd64/bin/java -ea -cp target/classes:lib:target/test_classes -Djava.library.path=target/cppbuild lib/llpl/TransactionalMemoryBlockTest;  /usr/lib/jvm/java-1.8.0-openjdk-amd64/bin/java -ea -cp target/classes:lib:target/test_classes -Djava.library.path=target/cppbuild lib/llpl/UnboundedMemoryBlockTest;
Exception in thread "main" java.lang.ExceptionInInitializerError
Caused by: java.lang.RuntimeException: Failed to open heap.
	at lib.llpl.AnyHeap.<init>(AnyHeap.java:53)
	at lib.llpl.Heap.<init>(Heap.java:16)
	at lib.llpl.Heap.getHeap(Heap.java:30)
	at lib.llpl.CopyMemoryTest.<clinit>(CopyMemoryTest.java:14)
Exception in thread "main" java.lang.RuntimeException: Failed to open heap.
	at lib.llpl.AnyHeap.<init>(AnyHeap.java:53)
	at lib.llpl.PersistentHeap.<init>(PersistentHeap.java:20)
	at lib.llpl.PersistentHeap.getHeap(PersistentHeap.java:34)
	at lib.llpl.PersistentMemoryBlockTest.main(PersistentMemoryBlockTest.java:12)
Exception in thread "main" java.lang.RuntimeException: Failed to open heap.
	at lib.llpl.AnyHeap.<init>(AnyHeap.java:53)
	at lib.llpl.Heap.<init>(Heap.java:16)
	at lib.llpl.Heap.getHeap(Heap.java:30)
	at lib.llpl.MemoryBlockCollectionTest.main(MemoryBlockCollectionTest.java:15)
Exception in thread "main" java.lang.RuntimeException: Failed to open heap.
	at lib.llpl.AnyHeap.<init>(AnyHeap.java:53)
	at lib.llpl.Heap.<init>(Heap.java:16)
	at lib.llpl.Heap.getHeap(Heap.java:30)
	at lib.llpl.MemoryBlockFreeTest.main(MemoryBlockFreeTest.java:12)
Exception in thread "main" java.lang.RuntimeException: Failed to open heap.
	at lib.llpl.AnyHeap.<init>(AnyHeap.java:53)
	at lib.llpl.Heap.<init>(Heap.java:16)
	at lib.llpl.Heap.getHeap(Heap.java:30)
	at lib.llpl.MemoryBlockEqualityTest.main(MemoryBlockEqualityTest.java:18)
Exception in thread "main" java.lang.RuntimeException: Failed to open heap.
	at lib.llpl.AnyHeap.<init>(AnyHeap.java:53)
	at lib.llpl.Heap.<init>(Heap.java:16)
	at lib.llpl.Heap.getHeap(Heap.java:30)
	at lib.llpl.MemoryBlockTest.main(MemoryBlockTest.java:13)
================================= All MultipleHeap tests passed ================================
================================= All MultipleTransactionalHeap tests passed ===================
Exception in thread "main" java.lang.RuntimeException: Failed to open heap.
	at lib.llpl.AnyHeap.<init>(AnyHeap.java:53)
	at lib.llpl.Heap.<init>(Heap.java:16)
	at lib.llpl.Heap.getHeap(Heap.java:30)
	at lib.llpl.SetMemoryTest.main(SetMemoryTest.java:14)
Exception in thread "main" java.lang.RuntimeException: Failed to open heap.
	at lib.llpl.AnyHeap.<init>(AnyHeap.java:53)
	at lib.llpl.Heap.<init>(Heap.java:16)
	at lib.llpl.Heap.getHeap(Heap.java:30)
	at lib.llpl.TransactionTest.main(TransactionTest.java:12)
Exception in thread "main" java.lang.RuntimeException: Failed to open heap.
	at lib.llpl.AnyHeap.<init>(AnyHeap.java:53)
	at lib.llpl.TransactionalHeap.<init>(TransactionalHeap.java:20)
	at lib.llpl.TransactionalHeap.getHeap(TransactionalHeap.java:34)
	at lib.llpl.TransactionalMemoryBlockTest.main(TransactionalMemoryBlockTest.java:13)
Exception in thread "main" java.lang.RuntimeException: Failed to open heap.
	at lib.llpl.AnyHeap.<init>(AnyHeap.java:53)
	at lib.llpl.Heap.<init>(Heap.java:16)
	at lib.llpl.Heap.getHeap(Heap.java:30)
	at lib.llpl.UnboundedMemoryBlockTest.main(UnboundedMemoryBlockTest.java:12)
Makefile:86: recipe for target 'tests' failed
make: *** [tests] Error 1
root@ubuntu:/home/wayne/llpl#

**Comment by asonje** [comment]
Hello, It looks like you are running out of memory. Unfortunately the README is a little out of date. You need at least 8GB to execute 'make tests'.  We will update the README shortly. if you dont have up to 8G we can figure out another way to validate your install. Thanks

**Comment by gwnet** [comment]
I only have 2G RAM to emulate the pmem. could you please update code and steps to play examples with only 2G pmem. very detail and more explanation is better. 
I want to write journal log with pmem. could you please suggest one library to me?

**Comment by gwnet** [comment]
may I know how it is going on from your side?

**Comment by asonje** [comment]
I have just modified the tests to use smaller heaps

**Comment by gwnet** [comment]
thank you so much. the build and UT is OK now. can you give me some command line example to play your example application?
I am new to Java

**Comment by asonje** [comment]
I also modified the examples to use smaller heaps. Here is how to run the MemoryBlockArray example
make
java -cp target/classes:src -Djava.library.path=target/cppbuild/ examples.array.MemoryBlockArray

You can also build the javadocs (run 'make docs') and in the package description section you will find a mini introduction to this library in addition to documentation of the API
